[api]
schemas = ["public", "mux"]

[functions.mux-webhook]
static_files = [ "./functions/mux-webhook/mux.toml" ]
enabled = true
verify_jwt = false
import_map = "./functions/mux-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/mux-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/mux-webhook/*.html" ]

[db.vault]
mux_supabase_service_role_key = "env(SUPABASE_SERVICE_ROLE_KEY)"
mux_supabase_url = "env(SUPABASE_URL)"
secret_key = "env(SUPABASE_SERVICE_ROLE_KEY)"
supabase_url = "env(SUPABASE_URL)"

[functions.video-embeddings]
enabled = true
verify_jwt = true
import_map = "./functions/video-embeddings/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/video-embeddings/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/video-embeddings/*.html" ]
